### ISSUE TITLE
Can't create workload with same name as another workload anywhere in Azure

### ISSUE THREAD

**Issue by agoodmiller** [Azure/missionlz#576] opened 2021-12-15 19:21 UTC
## Description
If i use the name tier3 as my workload name, the script errs out with (I do not have a tier3 in my subscription):
{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'tier3' is not valid according to the validation procedure. The tracking id is 'bf1a2831-9730-4642-a2b9-4c63159e64e4'. See inner errors for details.","details":[{"code":"PreflightValidationCheckFailed","message":"Preflight validation failed. Please refer to the details for the specific errors.","details":[{"code":"StorageAccountAlreadyTaken","target":"logsyhdfpdatgh7j2","message":"The storage account named logsyhdfpdatgh7j2 is already taken."}]}]}}

i ran it 4 different times and got the exact same error each time : "StorageAccountAlreadyTaken","target":"logsyhdfpdatgh7j2"

It seems that, forwheter reason, the  uniqueString(parameters('workloadName')) code in bicep isn't using anything other than the name to seed the UniqueString operation.
I assume it's also because someone else has used the script to create a tier3 and not deleted their test environment, 

## Steps to Reproduce

1.  create the initial MLZ
2.  set the workloadName to "tier3"
3. run the workload creation

## Expected behavior
it creates the new workload tier.

## Actual behavior
It errs out before even running

## Screenshots
![image](https://user-images.githubusercontent.com/9616765/146251128-4bcd0928-5067-46c2-a7fa-8eb2148b2f08.png)

## Additional context

Operating System:windows 11
Terraform Version: N/A
Cloud (public, Azure Government, etc.): Public

**Comment by glennmusa** [comment] 2021-12-15 21:31
Hi @agoodmiller thank you for submitting a bug with helpful context and reproduction steps.

There has, very recently, been updates to the New Workload example to reduce the likelihood of a naming collision for storage accounts: https://github.com/Azure/missionlz/pull/572

That latest version of the New Workload template should prevent this from occurring. If you still encounter this error with these latest steps, let us know: 

https://github.com/Azure/missionlz/tree/main/src/bicep/examples/newWorkload#deploy-the-example

**Comment by brooke-hamilton** [comment] 2021-12-16 16:12
@agoodmiller thank you for the bug report!

I did these steps to repro the issue, and I think like @glennmusa said the issue is likely fixed in very recent updates.
1. Deploy MLZ using defaults
2. Generate the `deploymentVariables.json` file from the deployment following these steps the [new workload readme](https://github.com/Azure/missionlz/tree/main/src/bicep/examples/newWorkload).
3. Deploy the new workload example using `--parameters workloadName=tier3`. 
The deployment succeeded.

I found some documentation errors while working through this and I'll address those too.

**Closed** 2021-12-16 18:40 UTC
Labels: bug
