### ISSUE TITLE
Do not use `resourcePrefix` alone when assigning names to resources with uniqueness requirements

### ISSUE THREAD

**Issue by glennmusa** [Azure/missionlz#498] opened 2021-11-01 19:57 UTC
## Description

We're generating a `resourcePrefix` value by default like so:

https://github.com/Azure/missionlz/blob/52882f61b11f802d00a72b350e034dfbaceef058/src/bicep/mlz.bicep#L465

And using that to assign names for certain resources that require uniqueness (things like Log Analytics Workspaces and Storage Accounts) like so:

https://github.com/Azure/missionlz/blob/52882f61b11f802d00a72b350e034dfbaceef058/src/bicep/mlz.bicep#L643

This can introduce failed deployments and unwanted behavior when a user specifies their own `resourcePrefix` value.

We should instead generate some uniqueness and use it for the resource names that require it.

## Steps to Reproduce

1.  Provide a user-supplied value for `resourcePrefix` like `foo`
2.  Certain items will occasionally fail on redeploy for resources that take longer to clean-up like certain security solutions for Log Analytics Workspaces

## Expected behavior

I can provide my own `resourcePrefix` value to a deployment and re-deploy as often as I want without error.

## Actual behavior

Certain items will occasionally fail on redeploy for resources that take longer to clean-up like certain security solutions for Log Analytics Workspaces

Cloud (public, Azure Government, etc.): public

**Comment by shawngib** [comment] 2021-11-02 13:40
This should merge with #439 as naming conventions will most likely solve for issues. Also think the issue that originally raised this has a different root cause that this will hide since despite documentation the LA Workspace doesn't require global uniqueness but following a naming convention like <resource type>-<prefix name/workload>-<location> would solve for. The primary concern is LA naming shouldn't be randomized since then its usage via portal, queries or coding becomes difficult.

**Comment by brooke-hamilton** [comment] 2021-11-03 13:29
Also please take #393 into consideration when addressing this bug.

**Comment by brooke-hamilton** [comment] 2021-11-03 15:00
The team recommends a spike on proving the implementation: a resource group that has a storage account that has a unique name based on a user-provided value, but is consistently generated so that idempotency is preserved.

**Comment by shawngib** [comment] 2021-11-11 18:24
Just wanted to place this here for reference of future need in unique names. Log Analytics workspace does not require it to be globally unique as per this GA announcement in commercial and gov: https://azure.microsoft.com/en-us/updates/general-availability-log-analytics-workspace-name-uniqueness-is-now-per-resource-group/ 

This may need further investigation as it may not be GA in all clouds.

**Comment by brooke-hamilton** [comment] 2021-12-07 15:05
This issue was resolved with #556

**Closed by brooke-hamilton** 2021-12-07 15:05 UTC
Labels: bug
